# -*- coding: utf-8 -*-
"""Project DS Jobs

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12GvvfN0IQeD9AXDJxPyk3T_aU2xMjuZA
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ds_salaries.csv')
print(df.head())

# Salary trend over years (Line Chart)

import seaborn as sns
import matplotlib.pyplot as plt

avg_salary_per_year = df.groupby('work_year')['salary_in_usd'].mean().reset_index()

# Plot
plt.figure(figsize=(8,5))
sns.lineplot(data=avg_salary_per_year, x='work_year', y='salary_in_usd', marker='o')
plt.title('Average Salary Over Years')
plt.xlabel('Year')
plt.ylabel('Average Salary (USD)')
plt.grid(True)
plt.show()

#Top 5 Job Titles by Average Salary (Bar Chart)

top_jobs = df.groupby('job_title')['salary_in_usd'].mean().sort_values(ascending=False).head(5)


plt.figure(figsize=(10,6))
sns.barplot(x=top_jobs.values, y=top_jobs.index, palette='viridis')
plt.title('Top 5 Job Titles by Average Salary')
plt.xlabel('Average Salary (USD)')
plt.ylabel('Job Title')
plt.show()

#Employment Type Proportions (Pie Chart)

employment_counts = df['employment_type'].value_counts()

# Plot
plt.figure(figsize=(6,6))
plt.pie(employment_counts, labels=employment_counts.index, autopct='%1.1f%%', startangle=140, colors=sns.color_palette('pastel'))
plt.title('Employment Type Distribution')
plt.axis('equal')
plt.show()

#Countries Offering the Most Jobs (Bar Chart)

jobs_by_country = df['company_location'].value_counts().head(10)

# Plot
plt.figure(figsize=(10,6))
sns.barplot(x=jobs_by_country.values, y=jobs_by_country.index, palette='mako')
plt.title('Top 10 Countries Offering Most Data Science Jobs')
plt.xlabel('Number of Jobs')
plt.ylabel('Country')
plt.show()

#US most popular data science job

us_jobs = df[df['company_location'] == 'US']

# Count job titles
us_job_counts = us_jobs['job_title'].value_counts().head(10)  # Top 10 most common

# Plot
plt.figure(figsize=(10,6))
sns.barplot(x=us_job_counts.values, y=us_job_counts.index, palette='coolwarm')
plt.title('Most Popular Data Science Job Titles in the US')
plt.xlabel('Number of Jobs')
plt.ylabel('Job Title')
plt.show()